configure

set system host-name rtr2

# Uplink back to rtr1
set interfaces ethernet eth0 description 'Uplink to rtr1'
set interfaces ethernet eth0 address '10.10.10.2/24'

# Additional internal segments off rtr2, if used
# set interfaces ethernet eth1 description 'Security subnet'
# set interfaces ethernet eth1 address '10.10.30.1/24'
# set interfaces ethernet eth2 description 'Attacker subnet'
# set interfaces ethernet eth2 address '10.10.40.1/24'

commit
save
exit